name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.3
  - pip:
      - sphinx>=7.2.6
      - sphinx-rtd-theme>=1.3.0
      - sphinx-autodoc-typehints>=1.25.2
      - sphinx-copybutton>=0.5.2
      - sphinx-book-theme>=1.1.0
      - sphinx-issues>=3.0.1
      - sphinx-design>=0.5.0
      - scanpydoc>=0.10.0
      - myst-parser>=2.0.0
      - ipykernel>=5.5.6
      - nbsphinx>=0.8.12
      - nbsphinx_link
      - pygments>=2.17.2
      - pytest>=7.4.4
      - nbmake>=1.4.6
      - scikit-learn>=1.4.0
      - pandas>=2.2.0
      - torch>=2.1.2
      - numpy>=1.26.3
      - pyBigWig>=0.3.22
      - anndata>=0.10.4

